theme: jekyll-theme-so-simple
skin: "/assets/css/skins/dark.css"
locale: en-GB
title: "Random Musings"
description: "A geek's eclectic contemplations"
baseurl: ""
url: "https://randommusings.netlify.com"
logo: "/assets/img/logo.webp"
date_format: "%B %-d, %Y / %l:%M %p"
read_time: true
words_per_minute: 200
mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Signika"
    weights: "400,700"
google_analytics:
disqus:
  shortname:
twitter:
  username:

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
feed:
  path: atom.xml
sass:
    style: compressed

# Pagination
paginate: 5
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

# Site Author
author:
  name: Divay Prakash
  picture: /assets/img/divayprakash.jpg
  email: divayprakash0@gmail.com
  twitter: divayprakash0
  links:
    - title: Twitter
      url: https://twitter.com/divayprakash0
      icon: fab fa-twitter
    - title: Email
      url: mailto:divayprakash0@gmail.com
      icon: fas fa-envelope

# Default frontmatter
jekyll_compose:
  default_front_matter:
    posts:
      layout    : post
      categories: []
      tags:       []
